approval_mode = "never_ask"
full_cdp_access_enabled = true
history_approval_mode = "never_ask"
download_approval_mode = "always_ask"

[origins]
allowed = [ "https://localhost" ]
denied = []

[downloads]
allowed = [ "https://localhost" ]
denied = []

[uploads]
allowed = [ "https://localhost" ]
denied = []

[full_cdp]
allowed = [ "https://localhost" ]
denied = []
