#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

prompt spaceship
autoload bashcompinit
bashcompinit

. ~/.zsh_pre_custom
. ~/.dotfiles/zsh/environment.zsh
. ~/.dotfiles/zsh/zsh-tweaks.zsh

if [[ -f /usr/local/etc/bash_completion.d/asdf.bash ]]; then
  . /usr/local/opt/asdf/asdf.sh
  . /usr/local/opt/asdf/etc/bash_completion.d/asdf.bash
fi

. ~/.dotfiles/zsh/mix_autocomplete.zsh
. ~/.dotfiles/zsh/git.zsh
. ~/.dotfiles/zsh/aliases.zsh
. ~/.dotfiles/zsh/post-hooks.zsh
. ~/.dotfiles/zsh/spaceship.zsh
. ~/.zsh_custom
