#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -s "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc" ]]; then
  source "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
fi

# Customize to your needs...

prompt spaceship
autoload bashcompinit
bashcompinit

. ~/.zsh_pre_custom
. ~/.dotfiles/zsh/environment.zsh
. ~/.dotfiles/zsh/zsh-tweaks.zsh
. ~/.dotfiles/zsh/mix_autocomplete.zsh
. ~/.dotfiles/zsh/git.zsh
. ~/.dotfiles/zsh/aliases.zsh
. ~/.dotfiles/zsh/post-hooks.zsh
. ~/.dotfiles/zsh/spaceship.zsh
. ~/.zsh_custom
