#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -s "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc" ]]; then
  source "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
fi

if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

# Customize to your needs...

prompt spaceship
autoload bashcompinit
bashcompinit

. ~/.zsh_pre_custom

dotfiles_root="${${(%):-%N}:A:h:h}"
. "$dotfiles_root/zsh/environment.zsh"
. "$dotfiles_root/zsh/zsh-tweaks.zsh"
. "$dotfiles_root/zsh/mix_autocomplete.zsh"
. "$dotfiles_root/zsh/git.zsh"
. "$dotfiles_root/zsh/aliases.zsh"
. "$dotfiles_root/zsh/post-hooks.zsh"
. "$dotfiles_root/zsh/spaceship.zsh"
unset dotfiles_root

. ~/.zsh_custom
